name: devOps

on:
  push:
    branches:
      - 'master'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.x]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # 使用 yarn 管理器
          cache: 'yarn'

      - name: yarn install & build
        run: |
          yarn install
          yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          # 上传的文件标识
          name: dist
          # 需要上传的文件或目录
          path: |
            ./
            !node_modules/
            !dbs/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          # 下载的文件标识
          name: dist
          # 下载后的文件名
          path: myBlog

      - name: Show Info
        run: |
          pwd
          ls -al
          ls myBlog -al

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Remote host
          REMOTE_HOST: vecchio.top
          # Remote user
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          # Remote port
          REMOTE_PORT: 22 # optional, default is 22
          # Source directory
          SOURCE: myBlog # optional, default is
          # Target directory
          TARGET: /root/workspace/vecchio/myBlog # optional, default is /home/REMOTE_USER/
          # Arguments to pass to rsync
          # ARGS: # optional, default is -rltgoDzvO
          # An array of folder to exclude
          # EXCLUDE: # optional, default is

      - name: SSH Restart
        uses: appleboy/ssh-action@master
        with:
          host: vecchio.top
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/workspace/vecchio/myBlog && yarn --production
            pm2 restart myBlog
